image: python:3.7

stages:
  - validate
  - sync


validate:
  stage: validate
  script:
    - pip install awscli
    - aws cloudformation validate-template --template-body "$(cat ./stacks/ecs-on-ec2.yml)"
    - aws cloudformation validate-template --template-body "$(cat ./stacks/mysql-serverless.yml)"
    - aws cloudformation validate-template --template-body "$(cat ./stacks/vpc-two-az.yml)"

s3:
  stage: sync
  script:
    - pip install awscli
    - aws s3 sync ./stacks s3://cf-templates-torijacarlos

github:
  stage: sync
  only:
    - master
  script:
    - mkdir ~/.ssh 
    - mv $GITHUB_PRIV_KEY ~/.ssh/github && chmod 400 ~/.ssh/github
    - cp .sshconfig ~/.ssh/config
    - ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
    - git remote add github git@github.com:TorijaCarlos/infrastructure.git
    - git checkout -B "$CI_BUILD_REF_NAME" "$CI_BUILD_REF"
    - git push github master -f