on: push

jobs:

  validate:
    runs-on: ubuntu-latest
    steps:
    - name: Set repository as working directory
      uses: actions/checkout@v2
    - name: Validate Cloudformation files
      run: make validate
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  sync:
    runs-on: ubuntu-latest
    needs: validate
    if: github.ref == 'refs/heads/master'
    steps:
    - name: Set repository as working directory
      uses: actions/checkout@v2
    - name: Sync files with S3 bucket
      run: aws s3 sync ./cloudformation s3://cf-templates-torijacarlos
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}